/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzee;

import client.Client;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author SELİN
 */
public class Yahtzee1 extends javax.swing.JFrame {

    public static Yahtzee1 ThisGame;
    public Thread tmr_slider;
    public String RivalSelection;
    public static String[] arr = {"1", "2", "3", "4", "5", "6"};
    ArrayList<JButton> butonlar = new ArrayList();
    int birler = 0;
    int ikiler = 0;
    int üçler = 0;
    int dörtler = 0;
    int besler = 0;
    int altilar = 0;
    int sayac = 0;

    /**
     * Creates new form Yahtzee1
     */
    public Yahtzee1() {
        initComponents();

        ThisGame = this;
        butonlar.add(zar1);
        butonlar.add(zar2);
        butonlar.add(zar3);
        butonlar.add(zar4);
        butonlar.add(zar5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        oyuncuİsim = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        fullhouse = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        smallst = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        largest = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        chance = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        bes = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        alti = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        bonus = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        threeof = new javax.swing.JButton();
        bir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        iki = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        üc = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        dört = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        fourof = new javax.swing.JButton();
        yahtzee = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        oyuncu1 = new javax.swing.JTextField();
        oyuncu2 = new javax.swing.JTextField();
        zar2 = new javax.swing.JButton();
        zar3 = new javax.swing.JButton();
        zar4 = new javax.swing.JButton();
        zar1 = new javax.swing.JButton();
        zar5 = new javax.swing.JButton();
        ZarAt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jButton35 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 268, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 381, -1, -1));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 536, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Ekran Görüntüsü (52).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 105, 510));
        getContentPane().add(oyuncuİsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -4, 153, 20));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        fullhouse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fullhouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullhouseActionPerformed(evt);
            }
        });

        jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        smallst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        smallst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallstActionPerformed(evt);
            }
        });

        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        largest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        largest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largestActionPerformed(evt);
            }
        });

        jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        chance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        chance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceActionPerformed(evt);
            }
        });

        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        bes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besActionPerformed(evt);
            }
        });

        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        alti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        alti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altiActionPerformed(evt);
            }
        });

        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        sum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        bonus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonusActionPerformed(evt);
            }
        });

        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        threeof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        threeof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeofActionPerformed(evt);
            }
        });

        bir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        bir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birActionPerformed(evt);
            }
        });

        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        iki.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        iki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikiActionPerformed(evt);
            }
        });

        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        üc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        üc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ücActionPerformed(evt);
            }
        });

        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        dört.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        dört.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dörtActionPerformed(evt);
            }
        });

        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        fourof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        fourof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourofActionPerformed(evt);
            }
        });

        yahtzee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        yahtzee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yahtzeeActionPerformed(evt);
            }
        });

        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(yahtzee, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chance, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(üc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dört, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fullhouse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(smallst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bonus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(largest, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fourof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(threeof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(üc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dört, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alti, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeof, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fourof, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullhouse, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smallst, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(yahtzee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 510));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 375, 34));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel2.setOpaque(false);

        oyuncu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu1ActionPerformed(evt);
            }
        });

        oyuncu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu2ActionPerformed(evt);
            }
        });

        zar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zar1ActionPerformed(evt);
            }
        });

        ZarAt.setBackground(new java.awt.Color(255, 153, 255));
        ZarAt.setText("Zar at");
        ZarAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZarAtActionPerformed(evt);
            }
        });

        txt2.setColumns(20);
        txt2.setRows(5);
        jScrollPane2.setViewportView(txt2);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        jButton35.setText("Gönder");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(oyuncu1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oyuncu2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(ZarAt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(zar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(zar2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(zar3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(zar4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(zar5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton35)
                .addGap(140, 140, 140))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oyuncu1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oyuncu2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zar2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zar3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zar4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zar5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ZarAt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 370, 450));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Adsız.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ZarAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZarAtActionPerformed
        // TODO add your handling code here:
        birler = 0;
        ikiler = 0;
        üçler = 0;
        dörtler = 0;
        besler = 0;
        altilar = 0;
        sayac = 0;
        Random r = new Random();

        zar1.setText(arr[r.nextInt(arr.length)]);
        zar2.setText(arr[r.nextInt(arr.length)]);
        zar3.setText(arr[r.nextInt(arr.length)]);
        zar4.setText(arr[r.nextInt(arr.length)]);
        zar5.setText(arr[r.nextInt(arr.length)]);
        for (int i = 0; i < butonlar.size(); i++) {
            if (butonlar.get(i).getText().equals("1")) {
                birler++;

            }
            if (butonlar.get(i).getText().equals("2")) {
                ikiler++;
            }
            if (butonlar.get(i).getText().equals("3")) {
                üçler++;
            }
            if (butonlar.get(i).getText().equals("4")) {
                dörtler++;
            }
            if (butonlar.get(i).getText().equals("5")) {
                besler++;
            }
            if (butonlar.get(i).getText().equals("6")) {
                altilar++;
            }

        }
        bir.setText(String.valueOf(1 * birler));
        iki.setText(String.valueOf(2 * ikiler));
        üc.setText(String.valueOf(3 * üçler));
        dört.setText(String.valueOf(4 * dörtler));
        bes.setText(String.valueOf(5 * besler));
        alti.setText(String.valueOf(6 * altilar));
        //three of a kind
        int sayi = 0;
        threeof.setText("0");
        if (birler >= 3) {
            sayi = birler * 1;
            sayi += (ikiler * 2) + (üçler * 3) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            threeof.setText(String.valueOf(sayi));
        } else if (ikiler >= 3) {
            sayi = ikiler * 2;
            sayi += (birler * 1) + (üçler * 3) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            threeof.setText(String.valueOf(sayi));
        } else if (üçler >= 3) {
             sayi = üçler*3;
            sayi += (birler * 1) + (ikiler * 2) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            threeof.setText(String.valueOf(sayi));
        } else if (dörtler >= 3) {
             sayi = dörtler*4;
            sayi += (birler * 1) + (ikiler * 2) + (üçler*3) + (besler * 5) + (altilar * 6);
            threeof.setText(String.valueOf(sayi));
        } else if (besler >= 3) {
             sayi = besler*5;
            sayi += (birler * 1) + (ikiler * 2) + (dörtler * 4) + (üçler*3) + (altilar * 6);
            threeof.setText(String.valueOf(sayi));
        } else if (altilar >= 3) {
            sayi = altilar * 6;
            sayi += (birler * 1) + (ikiler * 2) + (dörtler * 4) + (üçler*3) + (besler*5);
            threeof.setText(String.valueOf(sayi));
        }
        //four of a kind
        fourof.setText("0");
        int sayi1 = 0;
        if (birler >= 4) {
            sayi1 = birler * 1;
            sayi1 += (ikiler * 2) + (üçler * 3) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            fourof.setText(String.valueOf(sayi1));
        } else if (ikiler >= 4) {
            sayi1=ikiler * 2;
             sayi1 += (birler * 1) + (üçler * 3) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            fourof.setText(String.valueOf(sayi1));
        } else if (üçler >= 4) {
              sayi1=üçler * 3;
             sayi1 += (birler * 1) + (ikiler * 2) + (dörtler * 4) + (besler * 5) + (altilar * 6);
            fourof.setText(String.valueOf(üçler * 3));
        } else if (dörtler >= 4) {
             sayi1=dörtler * 4;
             sayi1 += (birler * 1) + (ikiler * 2) + (üçler * 3) + (besler * 5) + (altilar * 6);
            fourof.setText(String.valueOf(sayi1));
        } else if (besler >= 4) {
             sayi1=besler * 5;
             sayi1 += (birler * 1) + (ikiler * 2) + (üçler * 3) + (dörtler * 4) + (altilar * 6);
            fourof.setText(String.valueOf(sayi1));
        } else if (altilar >= 4) {
             sayi1=altilar * 6;
             sayi1 += (birler * 1) + (ikiler * 2) + (üçler * 3) + (dörtler * 4) + (besler * 5);
            fourof.setText(String.valueOf(sayi1));
        }
         //full house
         fullhouse.setText(String.valueOf("0"));
        if ((birler>=3||ikiler>=3||üçler>=3||dörtler>=3||besler>=3||altilar>=3)
                &&(birler>=2||ikiler>=2||üçler>=2||dörtler>=2||besler>=2||altilar>=2)) {
            fullhouse.setText(String.valueOf("25"));
        }
        // small straight
        smallst.setText(String.valueOf("0"));
        if ((birler==1 &&ikiler==1 &&üçler==1 &&dörtler==1) ||
              ( birler==1 &&ikiler==1 &&üçler==1 &&dörtler==1 &&besler==1)||
                (ikiler==1 &&üçler==1 &&dörtler==1 &&besler==1 &&altilar==1)) {
              smallst.setText(String.valueOf("30"));
            
        }
       
        //big straight 
         largest.setText(String.valueOf("0"));
        if ((birler ==1 && ikiler ==1 && üçler ==1 && dörtler==1 && besler==1)
                || (ikiler ==1 && üçler ==1 && dörtler==1 && besler==1 && altilar ==1)) {
         largest.setText(String.valueOf("40"));
        }
        //change
        int chng=0;
        chng += (birler * 1) + (ikiler * 2) + (üçler * 3) + (dörtler * 4) +(besler * 5)+ (altilar * 6);
        chance.setText(String.valueOf(chng));
        //yahtzee
        int yhtz=50;
          yahtzee.setText(String.valueOf("0"));
        if (birler==6 || ikiler==6 || üçler==6 || dörtler==6||
                besler==6||altilar==6) {
            yhtz+=50;
            yahtzee.setText(String.valueOf(yhtz));
        }
        //sum
        //bonus
    }//GEN-LAST:event_ZarAtActionPerformed

    private void oyuncu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu1ActionPerformed
        Client.Start("127.0.0.1", 2000);
    }//GEN-LAST:event_oyuncu1ActionPerformed

    private void oyuncu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oyuncu2ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        Mesaj msg = new Mesaj(Mesaj.Message_Type.Text);
        msg.content1 = txt1.getText();
        System.out.println(msg.content1);
        Client.Send(msg);
        txt1.setText("");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void zar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zar1ActionPerformed

    private void ikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikiActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "iki";
        m.content2 = iki.getText();
        Client.Send(m);
         iki.setVisible(false);
    }//GEN-LAST:event_ikiActionPerformed

    private void bonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonusActionPerformed

    private void chanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceActionPerformed
        // TODO add your handling code here:
         Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "chance";
        m.content2 = chance.getText();
        Client.Send(m);
        chance.setVisible(false);
    }//GEN-LAST:event_chanceActionPerformed

    private void threeofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeofActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "threeof";
        m.content2 = threeof.getText();
        Client.Send(m);
         threeof.setVisible(false);
    }//GEN-LAST:event_threeofActionPerformed

    private void fullhouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullhouseActionPerformed
        // TODO add your handling code here:
          Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "fullhouse";
        m.content2 = fullhouse.getText();
        Client.Send(m);
        fullhouse.setVisible(false);

    }//GEN-LAST:event_fullhouseActionPerformed

    private void fourofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourofActionPerformed
        // TODO add your handling code here:
         Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "fourof";
        m.content2 = fourof.getText();
        Client.Send(m);
         fourof.setVisible(false);
    }//GEN-LAST:event_fourofActionPerformed

    private void birActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birActionPerformed
        // TODO add your handling code here:
         Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "bir";
        m.content2 = bir.getText();
        Client.Send(m);
        bir.setVisible(false);
    }//GEN-LAST:event_birActionPerformed

    private void ücActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ücActionPerformed
        // TODO add your handling code here:
       Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "üc";
        m.content2 = üc.getText();
        Client.Send(m); 
         üc.setVisible(false);
    }//GEN-LAST:event_ücActionPerformed

    private void dörtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dörtActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "dört";
        m.content2 = dört.getText();
        Client.Send(m); 
         dört.setVisible(false);
    }//GEN-LAST:event_dörtActionPerformed

    private void besActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besActionPerformed
        // TODO add your handling code here:
          Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "bes";
        m.content2 = bes.getText();
        Client.Send(m); 
         bes.setVisible(false);
    }//GEN-LAST:event_besActionPerformed

    private void altiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altiActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "alti";
        m.content2 = alti.getText();
        Client.Send(m);
         alti.setVisible(false);
    }//GEN-LAST:event_altiActionPerformed

    private void smallstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallstActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "smallst";
        m.content2 = smallst.getText();
        Client.Send(m); 
        smallst.setVisible(false);
    }//GEN-LAST:event_smallstActionPerformed

    private void largestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largestActionPerformed
        // TODO add your handling code here:
        Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "largest";
        m.content2 = largest.getText();
        Client.Send(m); 
        largest.setVisible(false);
    }//GEN-LAST:event_largestActionPerformed

    private void yahtzeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yahtzeeActionPerformed
        // TODO add your handling code here:
       Mesaj m = new Mesaj(Mesaj.Message_Type.Secim);
        m.content1 = "yahtzee";
        m.content2 = yahtzee.getText();
        Client.Send(m); 
        yahtzee.setVisible(false);
    }//GEN-LAST:event_yahtzeeActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Linux".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yahtzee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yahtzee1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ZarAt;
    public javax.swing.JButton alti;
    public javax.swing.JButton bes;
    public javax.swing.JButton bir;
    public javax.swing.JButton bonus;
    public javax.swing.JButton chance;
    public javax.swing.JButton dört;
    public javax.swing.JButton fourof;
    public javax.swing.JButton fullhouse;
    public javax.swing.JButton iki;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton15;
    public javax.swing.JButton jButton17;
    public javax.swing.JButton jButton19;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton21;
    public javax.swing.JButton jButton23;
    public javax.swing.JButton jButton25;
    public javax.swing.JButton jButton27;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton35;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JButton largest;
    public javax.swing.JTextField oyuncu1;
    public javax.swing.JTextField oyuncu2;
    public javax.swing.JLabel oyuncuİsim;
    public javax.swing.JButton smallst;
    public javax.swing.JButton sum;
    public javax.swing.JButton threeof;
    public javax.swing.JTextArea txt1;
    public javax.swing.JTextArea txt2;
    public javax.swing.JButton yahtzee;
    private javax.swing.JButton zar1;
    private javax.swing.JButton zar2;
    private javax.swing.JButton zar3;
    private javax.swing.JButton zar4;
    private javax.swing.JButton zar5;
    public javax.swing.JButton üc;
    // End of variables declaration//GEN-END:variables
}
